ElectronServer/Electron/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^electron/', include('electron.urls')),
]

ElectronServer/electron/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # /electron
    url(r'^$', views.main_page, name='main_page'),

    # /electron/add_data
    url(r'^add_data/$', views.add_data, name='add_data'),

    # /electron/machines
    url(r'^machines/$', views.machines, name='machines'),

    # /electron/machines/<machine_id>
    url(r'^machines/(?P<machine_id>[0-9]+)/$', views.stamps, name="stamps"),

    # /electron/machines/<machine_id>/<stamp_id>
    url(r'^machines/(?P<machine_id>[0-9]+)/(?P<stamp_id>[0-9]+)/$', views.work_cycles, name="work_cycles"),

]

ElectronServer/electron/models.py
from django.db import models
from django.utils import timezone


def now_date():
    return timezone.now()


class Machine(models.Model):
    name = models.CharField(max_length=200)
    objects = models.Manager()

    def __unicode__(self):
        return self.name

    @staticmethod
    def delete_everything():
        Machine.objects.all().delete()


class Stamp(models.Model):
    name = models.CharField(max_length=200)
    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)
    objects = models.Manager()

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

    @staticmethod
    def delete_everything():
        Stamp.objects.all().delete()


class WorkCycle(models.Model):
    strikes_number = models.IntegerField(max_length=1000)
    date = models.DateTimeField(auto_now_add=True)
    stamp = models.ForeignKey(Stamp, on_delete=models.CASCADE)
    objects = models.Manager()

    @staticmethod
    def delete_everything():
        WorkCycle.objects.all().delete()

ElectronServer/electron/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
from .models import Machine, Stamp, WorkCycle
import json


def main_page(request):
    return render(request, 'electron/main_page.html')


def machines(request):
    all_machines = Machine.objects.all()
    return render(request, 'electron/machines.html', {'all_machines': all_machines})


def stamps(request, machine_id):
    machine = get_object_or_404(Machine, id=machine_id)
    return render(request, 'electron/stamps.html', {'machine': machine})


def work_cycles(request, machine_id, stamp_id):
    machine = get_object_or_404(Machine, id=machine_id)
    stamp = get_object_or_404(Stamp, id=stamp_id)
    return render(request, 'electron/workcycles.html', {'machine': machine, 'stamp': stamp})


@csrf_exempt
def add_data(request):
    if request.method == "POST":
        try:
            a = request.body.decode("utf-8")
            data = json.loads(a)

            if Machine.objects.filter(name=data['machine_id']).count() == 0:
                machine = Machine(name=data['machine_id'])
                machine.save()
            else:
                machine = Machine.objects.get(name=data['machine_id'])

            if Stamp.objects.filter(name=data['stamp_id'], machine=machine).count() == 0:
                stamp = Stamp(name=data['stamp_id'], machine=machine)
                stamp.save()
            else:
                stamp = Stamp.objects.get(name=data['stamp_id'], machine=machine)

            work_cycle = WorkCycle(strikes_number=int(data['strikes_number']), stamp=stamp)
            work_cycle.save()
        except:
            return JsonResponse({"success": False})

        return JsonResponse(data)

ElectronServer/electron/templates/electron/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/electron/style/header.css">
    <link rel="stylesheet" href="/static/electron/style/list.css">
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

ElectronServer/electron/templates/electron/machines.html
{% extends 'electron/base.html' %}
<title>{% block title %}Машини{% endblock %}</title>
{% block body %}

<body>
    <header class="header">
        <img src="/static/electron/images/logo.png" alt="" class="header__logo">
        <div class="header__info">
            <h2 class="header__title">Машини</h2>
        </div>
    </header>
    <div class="list">
		{% for machine in all_machines %}
			<a href="{% url 'stamps' machine.id %}" class="list__elem">{{ machine.name }}</a>
		{% endfor %}
	</div>
</body>

{%  endblock %}

ElectronServer/electron/templates/electron/main_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Electron</title>
</head>
<body>
    Electron!
</body>
</html>

ElectronServer/electron/templates/electron/stamps.html
{% extends 'electron/base.html' %}
<title>{% block title %}Штампи{% endblock %}</title>
{% block body %}

<body>
    <header class="header">
        <img src="/static/electron/images/logo.png" alt="" class="header__logo">
        <div class="header__info">
            <input type=button value="&#8592; Назад" onClick="javascript:history.back();" class="header__back-button">
            <h2 class="header__title">Штампи машини {{ machine.name }}</h2>
        </div>
    </header>
    <div class="list">
		{% for stamp in machine.stamp_set.all %}
            <a href="{% url 'work_cycles'  machine.id stamp.id %}" class="list__elem">{{ stamp.name }}</a>
        {% endfor %}
	</div>
</body>

{%  endblock %}

ElectronServer/electron/templates/electron/workcycles.html
{% extends 'electron/base.html' %}
<title>{% block title %}Робочі цикли{% endblock %}</title>
{% block body %}

<body>
    <header class="header">
        <img src="/static/electron/images/logo.png" alt="" class="header__logo">
        <div class="header__info">
            <input type=button value="&#8592; Назад" onClick="javascript:history.go(-1);" class="header__back-button">
            <h2 class="header__title">Робочі цикли штампу {{ stamp.name }}</h2>
        </div>
    </header>
    <div class="list">
        {% for work_cycle in stamp.workcycle_set.all %}
            <a class="list__elem">Дата: <span class="list__info">{{ work_cycle.date }}</span>
                <br>Кількість ударів: <span class="list__info">{{ work_cycle.strikes_number }}</span></a>
        {% endfor %}
	</div>
</body>

{%  endblock %}